import type { Fact } from '../../lib/tiny-rules-fp';

export const UNSET_FACT = 'unset';

export const MorrisGameFactKeys = [
  // is
  'isFirstMove',
  'isSecondMove',
  'isTurnWhite',
  'isTurnBlack',
  'isPlacingPhase',
  'isMovingPhase',
  'isLaskerPhase',
  'isFlyingPhase',
  'isRemoveMode',

  'isDrawPositionRepeatLimit',
  'isDrawNoMillsLimit',
  'isDraw',
  'isNoValidMoveWhite',
  'isNoValidMoveBlack',
  'isWinWhiteMillsMade',
  'isWinWhiteOpponentCount',
  'isWinWhiteOpponentNoValidMove',
  'isWinWhite',
  'isWinBlackMillsMade',
  'isWinBlackOpponentCount',
  'isWinBlackOpponentNoValidMove',
  'isWinBlack',
  'isWin',
  'isGameOver',

  // move is
  'moveIsCorrectColor',
  'moveIsCorrectType',
  'moveIsPossibleForPlace',
  'moveIsPossibleForMove',
  'moveIsPossibleForRemove',
  'moveIsPossibleForLasker',
  'moveIsPossibleForFlying',
  'moveIsPossible',
  'moveIsForbiddenOnFirstMove',
  'moveIsForbiddenOnSecondMove',
  'moveIsForbiddenInPlacingPhase',
  'moveIsValid',

  // move makes
  'moveMakesMill',
  'moveMakesRemoveMode',
  'moveMakesLaskerPhase',
  'moveMakesFlyingPhase',
  'moveMakesPlacingPhase',
  'moveMakesMovingPhase',
  'moveMakesNextTurnWhite',
  'moveMakesNextTurnBlack',
  'moveMakesDrawPositionRepeatLimit',
  'moveMakesDrawNoMillsLimit',
  'moveMakesDraw',
  'moveMakesNoValidMoveWhite',
  'moveMakesNoValidMoveBlack',
  'moveMakesWinWhiteMillsMade',
  'moveMakesWinWhiteOpponentCount',
  'moveMakesWinWhiteOpponentNoValidMove',
  'moveMakesWinWhite',
  'moveMakesWinBlackMillsMade',
  'moveMakesWinBlackOpponentCount',
  'moveMakesWinBlackOpponentNoValidMove',
  'moveMakesWinBlack',
  'moveMakesWin',
  'moveMakesGameOver',
] as const;
export type MorrisGameFactKeys = typeof MorrisGameFactKeys;

export type MorrisGameFacts = Record<MorrisGameFactKeys[number], Fact>;

export const INITIAL_MORRIS_GAME_FACTS: MorrisGameFacts = {
  // is
  isFirstMove: [false, UNSET_FACT],
  isSecondMove: [false, UNSET_FACT],
  isTurnWhite: [false, UNSET_FACT],
  isTurnBlack: [false, UNSET_FACT],
  isPlacingPhase: [false, UNSET_FACT],
  isMovingPhase: [false, UNSET_FACT],
  isLaskerPhase: [false, UNSET_FACT],
  isFlyingPhase: [false, UNSET_FACT],
  isRemoveMode: [false, UNSET_FACT],
  isDrawPositionRepeatLimit: [false, UNSET_FACT],
  isDrawNoMillsLimit: [false, UNSET_FACT],
  isDraw: [false, UNSET_FACT],
  isNoValidMoveWhite: [false, UNSET_FACT],
  isNoValidMoveBlack: [false, UNSET_FACT],
  isWinWhiteMillsMade: [false, UNSET_FACT],
  isWinWhiteOpponentCount: [false, UNSET_FACT],
  isWinWhiteOpponentNoValidMove: [false, UNSET_FACT],
  isWinWhite: [false, UNSET_FACT],
  isWinBlackMillsMade: [false, UNSET_FACT],
  isWinBlackOpponentCount: [false, UNSET_FACT],
  isWinBlackOpponentNoValidMove: [false, UNSET_FACT],
  isWinBlack: [false, UNSET_FACT],
  isWin: [false, UNSET_FACT],
  isGameOver: [false, UNSET_FACT],

  // move is
  moveIsCorrectColor: [false, UNSET_FACT],
  moveIsCorrectType: [false, UNSET_FACT],
  moveIsPossibleForPlace: [false, UNSET_FACT],
  moveIsPossibleForMove: [false, UNSET_FACT],
  moveIsPossibleForRemove: [false, UNSET_FACT],
  moveIsPossibleForLasker: [false, UNSET_FACT],
  moveIsPossibleForFlying: [false, UNSET_FACT],
  moveIsPossible: [false, UNSET_FACT],
  moveIsForbiddenOnFirstMove: [false, UNSET_FACT],
  moveIsForbiddenOnSecondMove: [false, UNSET_FACT],
  moveIsForbiddenInPlacingPhase: [false, UNSET_FACT],
  moveIsValid: [false, UNSET_FACT],

  // move makes
  moveMakesMill: [false, UNSET_FACT],
  moveMakesRemoveMode: [false, UNSET_FACT],
  moveMakesLaskerPhase: [false, UNSET_FACT],
  moveMakesFlyingPhase: [false, UNSET_FACT],
  moveMakesPlacingPhase: [false, UNSET_FACT],
  moveMakesMovingPhase: [false, UNSET_FACT],
  moveMakesNextTurnWhite: [false, UNSET_FACT],
  moveMakesNextTurnBlack: [false, UNSET_FACT],
  moveMakesDrawPositionRepeatLimit: [false, UNSET_FACT],
  moveMakesDrawNoMillsLimit: [false, UNSET_FACT],
  moveMakesDraw: [false, UNSET_FACT],
  moveMakesNoValidMoveWhite: [false, UNSET_FACT],
  moveMakesNoValidMoveBlack: [false, UNSET_FACT],
  moveMakesWinWhiteMillsMade: [false, UNSET_FACT],
  moveMakesWinWhiteOpponentCount: [false, UNSET_FACT],
  moveMakesWinWhiteOpponentNoValidMove: [false, UNSET_FACT],
  moveMakesWinWhite: [false, UNSET_FACT],
  moveMakesWinBlackMillsMade: [false, UNSET_FACT],
  moveMakesWinBlackOpponentCount: [false, UNSET_FACT],
  moveMakesWinBlackOpponentNoValidMove: [false, UNSET_FACT],
  moveMakesWinBlack: [false, UNSET_FACT],
  moveMakesWin: [false, UNSET_FACT],
  moveMakesGameOver: [false, UNSET_FACT],
};
