import type { Fact } from '../../lib/tiny-rules-fp';

export const UNSET_FACT = 'unset';

export const MorrisGameFactKeys = [
  'isFirstMove',
  'isTurnWhite',
  'isTurnBlack',
  'isPlacingPhase',
  'isMovingPhase',
  'isLaskerPhase',
  'isFlyingPhase',
  'moveMakesMill',
  'isRemoveMode',
  'isMoveCorrectColor',
  'isMoveCorrectType',
  'isMovePossibleForPlace',
  'isMovePossibleForMove',
  'isMovePossibleForLasker',
  'isMovePossibleForFlying',
  'isMovePossible',
  'isValidMove',
  'moveMakesNextTurnWhite',
  'moveMakesNextTurnBlack',
  'moveMakesDrawPositionRepeatLimit',
  'moveMakesDrawNoMillsLimit',
  'moveMakesDraw',
  'moveMakesNoValidMoveWhite',
  'moveMakesNoValidMoveBlack',
  'moveMakesWinWhite',
  'moveMakesWinBlack',
  'moveMakesWin',
  'moveMakesGameOver',
] as const;
export type MorrisGameFactKeys = typeof MorrisGameFactKeys;

export type MorrisGameFacts = Record<MorrisGameFactKeys[number], Fact>;

export const INITIAL_MORRIS_GAME_FACTS: MorrisGameFacts = {
  isFirstMove: [false, UNSET_FACT],
  isTurnWhite: [false, UNSET_FACT],
  isTurnBlack: [false, UNSET_FACT],
  isPlacingPhase: [false, UNSET_FACT],
  isMovingPhase: [false, UNSET_FACT],
  isLaskerPhase: [false, UNSET_FACT],
  isFlyingPhase: [false, UNSET_FACT],
  moveMakesMill: [false, UNSET_FACT],
  isRemoveMode: [false, UNSET_FACT],
  isMoveCorrectColor: [false, UNSET_FACT],
  isMoveCorrectType: [false, UNSET_FACT],
  isMovePossibleForPlace: [false, UNSET_FACT],
  isMovePossibleForMove: [false, UNSET_FACT],
  isMovePossibleForLasker: [false, UNSET_FACT],
  isMovePossibleForFlying: [false, UNSET_FACT],
  isMovePossible: [false, UNSET_FACT],
  isValidMove: [false, UNSET_FACT],
  moveMakesNextTurnWhite: [false, UNSET_FACT],
  moveMakesNextTurnBlack: [false, UNSET_FACT],
  moveMakesDrawPositionRepeatLimit: [false, UNSET_FACT],
  moveMakesDrawNoMillsLimit: [false, UNSET_FACT],
  moveMakesDraw: [false, UNSET_FACT],
  moveMakesNoValidMoveWhite: [false, UNSET_FACT],
  moveMakesNoValidMoveBlack: [false, UNSET_FACT],
  moveMakesWinWhite: [false, UNSET_FACT],
  moveMakesWinBlack: [false, UNSET_FACT],
  moveMakesWin: [false, UNSET_FACT],
  moveMakesGameOver: [false, UNSET_FACT],
};
